#!/bin/sh

#   fsl_reg - TBSS nonlinear registration
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2005-2008 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#
#
#   LICENCE
#
#   FMRIB Software Library, Release 6.0 (c) 2018, The University of
#   Oxford (the "Software")
#
#   The Software remains the property of the Oxford University Innovation
#   ("the University").
#
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Oxford
#   University Innovation ("OUI"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   fsl@innovation.ox.ac.uk quoting Reference Project 9564, FSL.
export LC_ALL=C

Usage() {
    echo ""
    echo "Usage: fsl_reg <input> <reference> <output> [options]"
    echo ""
    echo "Options:"
    echo " -e   : estimate transformation but don't apply it"
    echo " -a   : affine-only registration"
    echo " -FA  : use FNIRT config file optimised for FA data (FA_2_FMRIB58_1mm)"
    echo " -flirt \"flirt options\" : options to be passed onto flirt (inside double-quotes)"
    echo " -fnirt \"fnirt options\" : options to be passed onto fnirt (inside double-quotes)"
    echo ""
    exit 1
}

#echo $@
[ "$3" = "" ] && Usage
INPUT=`${FSLDIR}/bin/remove_ext $1`
REFERENCE=`${FSLDIR}/bin/remove_ext $2`
I2R=$3
shift 3

apply=1
affineonly=0
config="--config=T1_2_MNI152_2mm"
while [ _$1 != _ ] ; do
    if [ $1 = -e ] ; then
	apply=0
        shift
    elif [ $1 = -a ] ; then
        affineonly=1
        shift
    elif [ $1 = -FA ] ; then
        config="--config=FA_2_FMRIB58_1mm"
        shift
    elif [ $1 = -flirt ] ; then
        flirtopts=$2
        shift 2
    elif [ $1 = -fnirt ] ; then
        fnirtopts=$2
        shift 2
    else
        Usage
    fi
done

#echo apply=$apply affineonly=$affineonly config=$config
#echo flirtopts=\"$flirtopts\"
#echo fnirtopts=\"$fnirtopts\"

# do the registration
if [ `${FSLDIR}/bin/imtest ${INPUT}_mask` = 1 ] ; then
    INMASK="-inweight ${INPUT}_mask"
fi
${FSLDIR}/bin/flirt -ref $REFERENCE -in $INPUT $INMASK -omat ${I2R}.mat $flirtopts

if [ $affineonly = 1 ] ; then

    if [ $apply = 1 ] ; then
	${FSLDIR}/bin/flirt -ref $REFERENCE -in $INPUT -applyxfm -init ${I2R}.mat -out $I2R $flirtopts
    fi
    
else

    ${FSLDIR}/bin/fnirt --in=$INPUT --aff=${I2R}.mat --cout=${I2R}_warp $config --ref=$REFERENCE $fnirtopts

    if [ $apply = 1 ] ; then
	${FSLDIR}/bin/applywarp -i $INPUT -o $I2R -r $REFERENCE -w ${I2R}_warp
    fi

    # now estimate the mean deformation
    ${FSLDIR}/bin/fslmaths ${I2R}_warp -sqr -Tmean ${I2R}_tmp
    ${FSLDIR}/bin/fslstats ${I2R}_tmp -M -P 50 > ${I2R}_warp.msf
    ${FSLDIR}/bin/imrm ${I2R}_tmp
fi

