#!/bin/sh -f

#   slicesdir - call slicer on all input images and produce web page output
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#
#
#   LICENCE
#
#   FMRIB Software Library, Release 6.0 (c) 2018, The University of
#   Oxford (the "Software")
#
#   The Software remains the property of the Oxford University Innovation
#   ("the University").
#
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Oxford
#   University Innovation ("OUI"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   fsl@innovation.ox.ac.uk quoting reference Reference Project 9564, FSL.

if [ "$1" = "" ] ; then
    echo "Usage: slicesdir [-o] [-p <image>] [-e <thr>] [-S] <filelist>"
    echo "-o         : filelist is pairs ( <underlying> <red-outline> ) of images"
    echo "-p <image> : use <image> as red-outline image on top of all images in <filelist>"
    echo "-e <thr>   :  use the specified threshold for edges (if >0 use this proportion of max-min, if <0, use the absolute value)"
    echo "-S         : output every second axial slice rather than just 9 ortho slices"
    exit 1
fi

/bin/rm -rf slicesdir
mkdir slicesdir

echo '<HTML><TITLE>slicedir</TITLE><BODY BGCOLOR="#aaaaff">' > slicesdir/index.html

Width=1000
Compare=0
if [ "$1" = "-o" ] ; then
    Width=2000
    Compare=1
    shift
fi

if [ "$1" = "-p" ] ; then
    pairimage=$2
    shift 2
fi


edgeopts="";
if [ "$1" = "-e" ] ; then
    edgeopts="-e $2";
    shift 2
fi

sliceropts="$edgeopts -x 0.4 slicesdir/grota.png -x 0.5 slicesdir/grotb.png -x 0.6 slicesdir/grotc.png -y 0.4 slicesdir/grotd.png -y 0.5 slicesdir/grote.png -y 0.6 slicesdir/grotf.png -z 0.4 slicesdir/grotg.png -z 0.5 slicesdir/groth.png -z 0.6 slicesdir/groti.png"
convertopts="slicesdir/grota.png + slicesdir/grotb.png + slicesdir/grotc.png + slicesdir/grotd.png + slicesdir/grote.png + slicesdir/grotf.png + slicesdir/grotg.png + slicesdir/groth.png + slicesdir/groti.png"
if [ "$1" = "-S" ] ; then
    sliceropts="-S 2 1600 slicesdir/grota.png"
    convertopts="slicesdir/grota.png"
    shift
fi


number=`echo $* | wc -w`

i=0
while [ $i -lt $number ] ; do

    A=`${FSLDIR}/bin/remove_ext $1`
    echo $A

    if [ $Compare = 0 ] ; then
	${FSLDIR}/bin/slicer $A $pairimage -s 1 $sliceropts
	Q=`echo $A | sed "s/\//_/g"`
    else
	B=`${FSLDIR}/bin/remove_ext $2`
	${FSLDIR}/bin/slicer $A $B -s 1 $sliceropts
	Q=`echo $A | sed "s/\//_/g"`_to_`echo $B | sed "s/\//_/g"`
    fi

    ${FSLDIR}/bin/pngappend $convertopts slicesdir/${Q}.png
    /bin/rm -f slicesdir/grot?.png
    echo '<a href="'${Q}'.png"><img src="'${Q}'.png" WIDTH='$Width' >' ${Q}'</a><br>' >> slicesdir/index.html

    shift
    i=`echo "$i 1 + p" | dc -`
    if [ $Compare = 1 ] ; then
	shift
	i=`echo "$i 1 + p" | dc -`
    fi
done

echo '</BODY></HTML>' >> slicesdir/index.html

echo ''
echo 'Finished. To view, point your web browser at'
echo file:`pwd`/slicesdir/index.html

